### ISSUE TITLE
CSS mucked up

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#56]

**Comment by kgish** [comment]
Go to the following link: `admin/customize/css_html/1/css` and here is what you see:

```css
body {
    background: url(/uploads/default/original/1X/f7024dca7edc32faafe58bab733f13727c489f37.jpg);
    font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
    color: #333;
    line-height: 1.625rem;
}

body button, body select, body textarea {
    font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
}

.d-header #site-logo {
    padding-top: 15px;
    padding-bottom: 15px;
    max-height: none;
}

.d-header {
    height: auto;
    box-shadow: none;
    padding-top: 0;
}

.d-header .contents {
    margin: 0;
}

.d-header .panel {
    padding-top: 30px;
}

.primary-header {
    background: -webkit-linear-gradient(#555,#242423);
    background: -o-linear-gradient(#555,#242423);
    background: -moz-linear-gradient(#555,#242423);
    background: linear-gradient(#555,#242423);
    min-height:46px;
}

#main-outlet {
    padding-top: 125px;
}

.list-container {
    background-color: #fff;
}

.list-controls {
    background-color: #f5f5f5;
    padding: 20px 10px 0px 10px;
}

.topic-list a.title.visited, .topic-excerpt {
    color: #333 !important;
}

.nav-pills > li > a, .nav-pills > li.active > a, .nav-pills > li > a.active, .nav-pills > li > a:hover, .list-controls .btn {
    border-radius: 7px;
}

.list-controls a.badge-category {
    border-radius: 7px 0px 0px 7px;
}

.list-controls .category-breadcrumb a.badge-category.category-dropdown-button {
    margin-left: -4px;
    padding: 5px;
    width: 13px;
    border-radius: 0px 7px 7px 0px;
}

.nav-pills > li.active > a, .nav-pills > li > a.active {
    background-color: #50A7DD;
}

.nav-pills > li > a:hover {
    background-color: #b2b2b2;
    color: #fff;
}
.nav-pills > li.active > a:hover {
    background-color:#2991d1;
}

.topic-list-bottom {
    padding-left: 10px;
}

.topic-area {
    background-color: #fff; /*#f5f5f5*/
}

.footer {
    color: #fff;
    display: block;
    margin-top: 4rem;
    padding: 30px 0 40px;
    width: 100%;
    float: left;
    min-height: 16rem;
    background: -webkit-linear-gradient(#121111,#5d5e5c);
    background: -o-linear-gradient(#121111,#5d5e5c);
    background: -moz-linear-gradient(#121111,#5d5e5c);
    background: linear-gradient(#121111,#5d5e5c);
}

.footer__block {
    margin-bottom: 30px;
    width: 33.33333%;
    float: left;
}

.footer__block h3 {
    font-size: 21px;
    font-weight: 700;
    margin-bottom: 10px;
    line-height: 1.2;
}

.footer__block .nav {
    margin-bottom: 0;
    padding: 0 !important;
    list-style: none;
    display: block;
}

.footer__block .nav > li > a {
    position: relative;
    display: block;
    padding: 1rem 15px;
}

.footer__block .nav > li {
    position: relative;
    display: block;
    box-sizing: border-box;
}

.footer__block .nav > li > a {
    font-size: 14px;
    padding: 0;
    color: #fff;
}

.footer__block .nav > li > a:hover {
    color: #2991d1;
    text-decoration: underline;
}

#footer .container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-left: 15px;
    padding-right: 15px;
}

#footer .row {
    width: 1110px;
    margin-right: auto;
    margin-left: auto;
    padding-left: 15px;
    padding-right: 15px;
}

ul, ol, dd {
    margin: 0;
    padding: 0;
}
```
